package org.example.task_two;

public enum ViolationType {
    SPEEDING,
    ACDA,
    RED_TRAFFIC_LIGHT_DRIVING,
    PARKING_VIOLATION,
    SUSPENDED_LICENSE_DRIVING,
    CROSSWALK_STOP_FAILURE,
    STREET_RACING,
    RECKLESS_DRIVING
}
